---
# Save to pdf via Chrome

title: "Weekly Progress Reports"
description: |
author: Travis Sondgerath
date: "`r Sys.Date()`"
output:
  html_document:
    # toc: true
    # toc_depth: 2
    # toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

```

# August 17th - September 6th, 2020

**Important Note**

The contract between CDC and IRESSEF was terminated as of November, 2019. As such some activities were left unfinished. Progress documentation was resumed August 17th to track progress beginning with the new contract aimed at resuming activities under the direction of ASLM and CDC. As such the format of the progress reports has changed per instructions from ASLM.

## Key Activities by Project Objective

1.	Support the development of Ona surveys to be used to in the field to collect data on newly deployed equipment, as well as to update data on existing equipment already in circulation 
  * Created and sent documentation on what I need to revise the surveys to make them useful for actual use in the field
  * Sent documentation on connecting to forms in ODK Collect
2.	Support the deployment of an ASLM administered reporting platform
  * Created an Amazon Web Services Account and added a developer user
  * Began configuring the server to run the eTool code.See below for related issues. 

## Challenges

* Need feedback on the forms and must have someone attempt to use them
* Currently having issues configuring the environment in AWS. The free to use tier may not have enough computing power to install key packages, This is not unique to AWS and would be an issue on any cloud provider. In order to bypass this issue as well as the payment issue, we may want to provision a paid shinyapps.io account. The environment would already be set to accept the eTool code, authentication comes with the Standard and Professional accounts, and 10,000 active hours comes with the professional tier which is enough to run an application constantly with hours to spare for other testing applications. Additionally, this service could be paid up front which allows me to invoice the cost of the service as opposed to running a pay as you go platform like Amazon Web Services. 
  + Standard plan - \$99/month or \$1,100/year
  + Professional Plan - \$299/month or \$3,300/year


# April 1st - April 7th, 2019

## Progress Items

* Created an RStudio Cloud **[lesson](https://travis-shinin-spot.shinyapps.io/new_equip_form/)** on maintaining and changing the code for the new equipment **[form](https://travis-shinin-spot.shinyapps.io/new_equip_form/)**. 
* Plan to also create one for making equipment life books and generating a basic report using equipment data. 

## Agenda Items

1. I would suggest instead of having our regular call at the normal time on Wednesdays, that we see if the larger group would like a demonstration on a different day. Perhaps either at 7 am or 11 am?

# March 25th, - March 31st, 2019

## Progress Items
* Created mandatory fields in the **[form](https://travis-shinin-spot.shinyapps.io/new_equip_form/)** for new equipment.
* Finished annotations for RStudio Cloud **[workspace](https://rstudio.cloud/project/255745)** lesson on maintaining the eTool code
* Updated final report. 

## Agenda Items

1. Wanted to make sure to let everyone know that I was compensated for January/February work. Have invoiced Mimi for March. 
2. Discuss date proposals for larger group discussion. Good time to update them on progress.
3. Discuss RStudio Cloud Workspace. 

# March 18th - March 24th, 2019

## Progress Items

* Made revisions to the **[form](https://travis-shinin-spot.shinyapps.io/new_equip_form/)** for new equipment. It is now possible for some of the drop downs to type in an additional option if not already shown.
* Created a **[user guide](https://github.com/paceafenet/etool_dev/blob/master/New%20Equipment%20Form%20User%20Guide.pdf)** for the form referenced above.
* Added more demo courses to the project RStudio Cloud **[workspace](https://rstudio.cloud/project/255745)**.
* Added material to the **[Final Report](https://paceafenet.github.io/final_report/)**.

## Agenda Items

1. Discuss form for new equipment
2. User guide
3. RStudio Cloud
4. Final Report

# March 12th - March 17th, 2019

## Progress Items

* Created a **[form](https://travis-shinin-spot.shinyapps.io/new_equip_form/)** to add data for new equipment to the eTool database. Added link to it in eTool.
* Created a project **[workspace](https://rstudio.cloud/project/255745)** that could be used to build capacity in R programming so that the eTool could be adapted in country.

## Agenda Items

1. New form created - go over
2. Discuss conversation with Theresa and RStudio Cloud test work space.
3. Discuss RStudio Connect updates below. 
4. Payment delay. Need status update, can provide further info if necessary. 

# March 4th - March 11th, 2019

## Progress Items

* Discussed current progress with Theresa. Specifically, we discussed issues regarding deploying the tool to the field and issues with partners in-country being able to fully adapt, maintain, and use data entered/altered using the eTool.
* Installed RStudio Connect QuickStart. This is essentially a trial version of RStudio Connect that you run locally on your machine rather than on a server. This is the service I would recommend to CDC as other analytic tools are essentially for reporting only. You can develop reports and administrate access to those reports, however users/viewers cannot alter underlying data using those reporting tools. 
* Updated Final report.
* Updated eTool to include second page with form for uploading data for a single new piece of equipment. 

## Agenda Items

1. Discuss RStudio Connect layout and admin tools.
2. Discuss RStudio Cloud.
3. Discuss additions to eTool.

# Feb 25th - March 3rd, 2019

## Progress Items

* I have begun developing more technical documentation on adapting the eTool code for future use. 

## Agenda Items

1. Discuss eTool outline.
2. Discuss technical guidance. 
3. Payment request for January submitted to CDC. Any to get more timely payment?

# Feb 11 - Feb 17, 2019 + Feb 18 - Feb 24th 

## Progress Items

* Developed outline for eTool (Deliverable 2). Refined the outline further. This outline can serve as a user manual for those tracking equipment data in the field. A technical user manual will complement this as a component of deliverable 3. I would like to share this document with the larger equipment maintenance group.
  + Output as pdf and added to project home page.
* Discuss whether or not I am ready to develop a technical user manual for maintaining the eTool code. 

## Agenda Items

1. Discuss eTool outline.
2. Discuss considering Deliverable 1 as completed. 

# Feb 4 - Feb 10, 2019

## Progress Items

* Made eTool dev repository private and sent Mimi receipt for 12 month subscription. Sent email alluding to who I would like to add as collaborators. They will need to create GitHub accounts to view, discussed in email to Ruth and Fatima.
* eTool dev repository set as private, however, I left the final report and progress reports repositories as public. There is nothing sensitive and the websites developed from these repositories are worth showing outsiders for accountability and to describe our work. 

## Agenda Items

1. I went through the equipment inventory from Ruth that she received from Biologic Solutions. It could be useful if these are in the actual Cameroon data, however, is this all the information they have about their equipment? Currently, there is nothing other than type, do they have service dates? Or perhaps this is just info they don't have? I would really like to know how specific their data is.
2. Discuss my email regarding adding those involved with the equipment maintenance project as collaborators on GitHub if not resolved already. 
3. **Good time to discuss SOW:** 
Deliverable 1 in SOW - *Support the review of existing Nigeria/Cameroon country data (Deliverable – data reviewed, interim report* - Due Date: December, 2018
    + I have reviewed and **[reported](https://github.com/paceafenet/etool_dev/blob/master/existing_lab_data_exploration.md)** on the current state of the Nigeria data from the past laboratory assessment. 
    + I also have reached out to the Cameroon Team repeatedly, and have not had any success in obtaining their data. I understand that ASLM/IRESSEF/CDC will be meeting in Nigeria soon (perhaps even this week) where it is possible progress could be made on this front in person.
    + I would like to consider this deliverable fulfilled. Although, I would be happy to review their data if it is made accessible to me in the very near future. If we cannot obtain it during February I would like to close this deliverable and consider it completed.
4. Deliverable 2 in SOW - *Collaborate with and lead the IT Task Force to identify the best systems, processes and tools to meet the program goals (Deliverable – weekly calls with Task Force to support review of data and development of eTool; final list of eTool features outlined* - Due Date: February, 2019
    + We have consistently held weekly meetings and I have provided updates on progress. Ruth has been the most consistent attendee on the progress management side and I believe my progress has been swift and satisfactory.
    + There are a few more changes I plan to make to the eTool, however, I believe that the core functionality and layout is set. If it is agreed upon that the current tool is acceptable, I would like to begin creating an outline of eTool features and post this report to GitHub to satisfy this deliverable. 
    + Finalizing the eTool layout and working on the outline will allow me to begin developing metrics for a dashboard to support project and laboratory supervisors in assessing maintenance activities (part of SOW deliverable 3). 


# Jan 28 - Feb 3, 2019

## Progress Items

* eTool Updates - Added confirmation message once the user selects the update date button. This will inform them that they have altered the underlying equipment data. Additionally, I have added popup boxes to inform them they have altered the underlying data. 
* Updated the final report, specifically the R libraries section. 
* Reviewed contract deliverables. Worth discussing the current state (see agenda items). 

## Agenda Items

1. I received my first wire which includes the fees for subscriptions for GitHub and shinyapps.io. Other than those who have been included in the IT calls as well as the the larger equipment maintenance group, is there anyone else I should include on the access lists for these accounts? 
2. Discuss current layout of the tool. Really coming along nicely.
3. Deliverable 1 in SOW - *Support the review of existing Nigeria/Cameroon country data (Deliverable – data reviewed, interim report* - Due Date: December, 2018
    + I have reviewed and **[reported](https://github.com/paceafenet/etool_dev/blob/master/existing_lab_data_exploration.md)** on the current state of the Nigeria data from the past laboratory assessment. 
    + I also have reached out to the Cameroon Team repeatedly, and have not had any success in obtaining their data. I understand that ASLM/IRESSEF/CDC will be meeting in Nigeria soon (perhaps even this week) where it is possible progress could be made on this front in person.
    + I would like to consider this deliverable fulfilled. Although, I would be happy to review their data if it is made accessible to me in the very near future. If we cannot obtain it during February I would like to close this deliverable and consider it completed.
4. Deliverable 2 in SOW - *Collaborate with and lead the IT Task Force to identify the best systems, processes and tools to meet the program goals (Deliverable – weekly calls with Task Force to support review of data and development of eTool; final list of eTool features outlined* - Due Date: February, 2019
    + We have consistently held weekly meetings and I have provided updates on progress. Ruth has been the most consistent attendee on the progress management side and I believe my progress has been swift and satisfactory.
    + There are a few more changes I plan to make to the eTool, however, I believe that the core functionality and layout is set. If it is agreed upon that the current tool is acceptable, I would like to begin creating an outline of eTool features and post this report to GitHub to satisfy this deliverable. 
    + Finalizing the eTool layout and working on the outline will allow me to begin developing metrics for a dashboard to support project and laboratory supervisors in assessing maintenance activities (part of SOW deliverable 3). 

# Jan 21 - Jan 27, 2019

## Progress Items

* I was able to get the data behind the eTool (googlesheets) to update based on user input in the eTool. At first I had trouble reconciling the date formats of the dates from my original "fake" data with the new data added by the user. I was able to get things working correctly but my initial approach would have slowed the tool down too much even for demonstration purposes. I am re-worked my approach and now it is functioning correctly. The tool now includes core functionality either outlined in the contract or discussed during calls, namely it can:
    + Give a summary of the current state of the equipment
    + Allow the user to update equipment data - I'll have to play around with the eTool behavior but I think the user has to refresh the app for changes to be reflected.
    + The eTool will only show the most recent data for each piece of equipment, however the original data is retained in the underlying googlesheet, allowing for the development of equipment "life books."
* As a follow-up to an inquiry from Theresa, I created an example code that could send alerts via email alerting partners to examine the eTool - **[See example](https://github.com/paceafenet/etool_dev/blob/master/email_proof_of_concept.Rmd)**. R library used for this (blastula) can be found in the **[final report](https://paceafenet.github.io/final_report/)**. Additionally, I created a pricing guide for row level security as well as report scheduling features in commercial software - priced out RStudio Connect, PBI, Tableau. Summary and slides sent to Theresa (Fatima and Ruth CC'd) - **[See Slides](https://github.com/paceafenet/etool_dev/blob/master/Quick%20Pricing%20Guide%20%E2%80%93%20analytics%20reporting%20tools.pptx)**. Did she get it? Might have gone to spam.

## Agenda Items

1. Follow-up on any action items from larger group meeting. Discuss the PowerPoint in the eTool repository (see link above).
2. Discuss the current state of the layout and the addition of 'reactive' events. 
3. Briefly discuss ONA thoughts.
4. Consider follow-up with Cameroon team for their data. Worth getting to add to report of current data state. Gives us good information for what we 'need' for the tool as well as completing one of the project deliverables.

# Jan 7, - Jan 13 + Jan 14, - Jan 20, 2019

## Progress Items

**Note:** Combined last week's progress with this week's since no one was on for the Wed IT call. 

* As a follow-up to an inquiry from Theresa, I created an example code that could send alerts via email alerting partners to examine the eTool. R library used for this (blastula) can be found in the (([final report](https://paceafenet.github.io/final_report/)**. Additionally, I created a pricing guide for row level security as well as report scheduling features in commercial software - priced out RStudio Connect, PBI, Tableau. Summary and slides sent to Theresa (Fatima and Ruth CC'd). 
* Sent Invoice 2 for payment to Mimi. First invoice still in progress for payment.
* I changed the UI in app. First I added a couple ways to alter the underlying data and also condensed the interface layout. Still in progress to make sure it's working properly. Retains historical data as well. 
* Finalized initial layout of the tool including background colors, text color, and object. Functionality to edit data to come later. Added custom layout for mobile. Currently, I have hidden several charts that appear on the desktop app from the mobile app. Will plan to change the UI for mobile.
* Posted most up to date app to shinyapps.io. 
* Sent Ruth the **[link](https://travis-shinin-spot.shinyapps.io/etool_dev/)** to the app.
* Added eTool link to the project home page.
* Presented the current layout to the larger group for feedback.
* Read up on ONA document. Usable API and seems reasonable, the question would be WHO would take ownership in the field and be responsible for entering data?

## Agenda Items

1. Have not heard back from Mimi as of yet. Need feedback on invoice. 
2. Follow-up on any action items from larger group meeting. Discuss the PowerPoint in the eTool repository (see link above).
3. Discuss the current state of the layout and the addition of 'reactive' events. 
4. Briefly discuss ONA thoughts.
5. Consider follow-up with Cameroon team for their data. Worth getting to add to report of current data state. Gives us good information for what we 'need' for the tool as well as completing one of the project deliverables. 

# Dec 31, 2018 - Jan 6, 2019

## Progress Items
* Working on layout of eTool. Currently have a map, charts describing the current state of the data, as well as tables in a single layout. 
* Updated final report with additional libraries used in eTool development (DT and leaflet). 

## Agenda Items
1. Current state of invoice. Sent, 12/26, need feedback on format and payment to progress.
2. Discuss eTool current state. I have made significant progress, on the layout and functionality of the tool. I still need to add the ability to edit the data and have these changes captured in the app. However, the layout is coming along nicely.
If you are not accessing the meeting via a computer, here is a **[link](https://github.com/paceafenet/etool_dev/blob/master/screen%20grabs/eTool%20pic%20one%201_7_19.jpg)** to a screen grab of the current layout.
3. See updates in the **[Final Report](https://paceafenet.github.io/final_report/)** for additional tools used during development.
4. Have reached out to Cameroon a few times, hoping to reconnect now that most people should be back from leave. 

# Dec 17 - Dec 30, 2018

## Progress Items

* During the Dec 18 call it was requested that in addition to the website version of the progress reports, I also make the report available as a pdf or word document if possible. It took a bit of figuring out, but I will now be asking Ruth to attach the most up to date version of the progress report as a pdf to each week's meeting invite as well as include the link to the progress report site. 
* Drafted and sent the first invoice for first five weeks of work.
* Finalized the Nigeria report. During the Dec 18 call it was also requested that I also summarize the service providers in the Nigerian assessment data. Note to Travis: Go to the **[report](https://github.com/paceafenet/etool_dev/blob/master/existing_lab_data_exploration.md)** and summarize this additional table. 
* Began developing eTool application code based on fake data set. 

## Agenda Items
1. Discuss eTool layout. So far working on the map to show what labs need attention (discuss criteria), general layout scheme developed.
2. Discuss Nigeria report updates.

# Dec 3 - Dec 16, 2018

## Progress Items

* Reached out to Cameroon for in-country data
* Reached out to Mimi for clarification regarding invoicing procedures. Will await her response before upgrading current GitHub account to Developer version. 
* My plan is to use Google Sheets as the data source for the eTool, and use the eTool to edit the data in Google Sheets. I will use an approach similar to this **[app](https://jennybc.shinyapps.io/10_read-write-private-sheet/)** (code **[here](https://github.com/jennybc/googlesheets/tree/master/inst/shiny-examples/10_read-write-private-sheet))**. I have authenticated the project Google account using this approach and can access a toy data set I created in Google Sheets. 
* Added **[Nigeria Data Report](https://github.com/paceafenet/etool_dev/blob/master/existing_lab_data_exploration.md)** to the project home page. A link to this report is included here and on the home page. A more aesthetically pleasing copy of the report has also been sent as an attachment ahead of this meeting. Full process and initial results contained in this report, major conclusions and questions resulting from these analyses included below in the agenda items.

## Agenda Items

1. Follow-up after initial exploration of Nigeria data.
* For more accurate location of lab equipment we would will need latitude and longitudes of labs, or at least more descriptive addresses. Geo coded existing addresses to limited success. 
* These data can be used for demonstration as they are now, but the eTool will be most useful with a complete inventory of equipment at each lab.
* Information initially identified as essential including calibration dates which could be used to identify when equipment is due for maintenance, calibration, or retirement is largely dependent on manufacturer specifications. From the data as it is currently, it would not be possible to identify when equipment should next be serviced. This point will require further discussion.

# Nov 22 - Dec 2, 2018

## Progress Items

* Created a project GitHub account and associated repositories. Currently there are three repositories; one that will contain all eTool development code, another that will host a **[GitHub Page](https://pages.github.com/)** for progress, and a third repository that will host a GitHub page for the project's **[Final Report](https://paceafenet.github.io/final_report/)**.
* Created associated RProject file for each repository and made templates that will be used to populate the GitHub pages referenced above.
* Began writing the outline and portions of the Final Report page. This will be a living document that serves as a road map of how this project was completed.
* Began reviewing Nigeria data. 
* Created 'fake' equipment data should we be unable to obtain sufficient equipment data from the field.

## Agenda Items

1. It is important that I store all code and progress reports using GitHub both for accountability and to facilitate reproduction of this project in the future. It is worth considering what should be kept in the repository. For example, the data I receive from Nigeria and Cameroon in country partners may include information we would not want to be accessible in GitHub.
  * Comments on the GitHub Pages layout?
  * Thoughts on where to store in country data?
2. Lab-level Metrics for evaluation;
  * Equipment up time vs downtime
  * Avg number of equipment past due for repair or servicing
  * Elapsed time after past due 
  * What are acceptable levels for the above?
3. Nigeria Data: Quite a bit there, maybe not everything we would need. Biggest issue; for each machine type, one row per lab, allows them to say more than one machine but only one serial number showing.Took a while to successfully import the data from the Nigeria Access Databases, solved it. Still working on initial data exploration, will update on next call.
4. When can we hope to obtain in-country data from Cameroon? 
5. When should I purchase and invoice a shinyapps.io account?

# Sep 16 - Oct 31, 2019

## Progress Items

* Research
    + Read through online documents for the best approach to collecting data using ODK technologies. My sense is that the best way to go about it is to use a combination of the [Ona](https://ona.io/about-us.html) platform and [ODK Collect](https://docs.opendatakit.org/collect-intro/) for Android devices. 
    + ODK recently released [ODK Central](https://docs.opendatakit.org/central-intro/), a way for organizations to host their data collection on a private server. ODK Aggregate is a similar service and can be hosted either on-premises or even on inexpensive cloud-based platforms like Digital Ocean. My impression is that Ona is very user friendly. It is very easy to export data from Ona in a number of formats, upload forms configured in Excel files as surveys, and to manage forms and projects through a free account.
    + Researched ODK Briefcase for offline capabilities. I do not think ODK Briefcase is necessary for this project. Briefcase is essentially a local copy of a survey project directory complete with all forms, meta data, and responses. The advantage of using briefcase is that you can take responses without connection, upload them via SD card to a Briefcase directory on a laptop, and then upload the whole directory to an online project directory hosted on a server at a later time once you have an internet connection. I do not think this is necessary. ODK Collect and Ona are sufficient for this project. ODK Collect allows the user to capture responses in blank form(s). Their responses are cashed in the device browser, and then submitted to the Ona host once they have online connection. 
* Development
    + Created forms using [ODK Build](https://docs.opendatakit.org/build-intro/), a tool created by ODK to make creating ODK forms with a Graphical User Interface possible. ODK forms are uploaded to platforms that accept forms as Excel files but must be formatted in a very specific way. ODK Build allows the user to easily design the appearance of a form, export it to Excel, and then upload that file to platforms like Ona. The four forms created include the Equipment Activity Form - documentation of Maintenance Activities, Equipment Information Form - to document newly added equipment and any changes to equipment information, Request Maintenance - to request maintenance for a specific piece of equipment, Request Calibration - to request calibration for a specific piece of equipment. 
    + Created a project account in Ona to manage forms and submitted dummy responses to these forms. 
    + Figured out how to pull data from Ona forms. 

# Nov 1 - Nov 29, 2019

## Progress Items
<!-- Be sure to also go through OneNote for additional progress items -->
* Created a pipeline to get data from Ona and feed into a reporting application.
    + Added constants to add to expected equipment activity dates
    + Created logic to pull most recent data from relevant forms
    + Created logic to flag equipment in need of attention for various reasons. 
    + Still allows for reporting on historical data. 
    + Improved ease of querying data from Ona.
    + Created additional forms for Ona using Form Builder; request forms, form to enter or change equipment info, form to enter equipment activity interaction.
    + Pipeline includes logic for unduplication of data where appropriate.
* Created report from Ona data that will be used to show;
    + Current data describing equipment
    + Historical equipment data including changes to equipment location, and responsible staff for maintenance
    + Requests for equipment calibration and maintenance. 
    + Key summary measures as well as detailed information describing equipment
* Created documentation for existing reports
    + Outline describing expected deliverables
    + Documentation to support the use of Ona surveys
    + Documentation to server as guidance for navigating the eTool






























